name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Shell script lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck main.sh

  syntax:
    name: Bash syntax check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check bash syntax
        run: bash -n main.sh

  test:
    name: Test script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: ./main.sh
