name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax:
    name: Bash syntax check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check bash syntax
        run: bash -n main.sh

  test:
    name: Test script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: ./main.sh
